// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CameraControl

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_StartScreen
void ui_StartScreen_screen_init(void);
lv_obj_t *ui_StartScreen;
lv_obj_t *ui_StartTabView;
lv_obj_t *ui_WirelessTabPage;
void ui_event_StartBluetoothButton( lv_event_t * e);
lv_obj_t *ui_StartBluetoothButton;
void ui_event_Image2( lv_event_t * e);
lv_obj_t *ui_Image2;
lv_obj_t *ui_Label7;
lv_obj_t *ui_StartWiFiButton;
lv_obj_t *ui_Image4;
lv_obj_t *ui_Label8;
lv_obj_t *ui_SettingsTabPage;
lv_obj_t *ui_WiFiApiContainer;
lv_obj_t *ui_Label2;
void ui_event_ccApiCheckbox( lv_event_t * e);
lv_obj_t *ui_ccApiCheckbox;
void ui_event_ptpCheckbox( lv_event_t * e);
lv_obj_t *ui_ptpCheckbox;
lv_obj_t *ui_MaintenanceContainer;
lv_obj_t *ui_Label4;
void ui_event_RestartControllerButton( lv_event_t * e);
lv_obj_t *ui_RestartControllerButton;
lv_obj_t *ui_Label3;
void ui_event_CalibrateTouchPanelButton( lv_event_t * e);
lv_obj_t *ui_CalibrateTouchPanelButton;
lv_obj_t *ui_Label1;
void ui_event_ResetAllSettingsButton( lv_event_t * e);
lv_obj_t *ui_ResetAllSettingsButton;
lv_obj_t *ui_Label5;
lv_obj_t *ui_AboutTabPage;
lv_obj_t *ui_AppNameLabel;
lv_obj_t *ui_AppVersionLabel;
lv_obj_t *ui_AppCopyrightLabel;
lv_obj_t *ui_AppLicenseLabel;
lv_obj_t *ui_Apache2LicenseLabel;


// SCREEN: ui_BluetoothScreen
void ui_BluetoothScreen_screen_init(void);
void ui_event_BluetoothScreen( lv_event_t * e);
lv_obj_t *ui_BluetoothScreen;
void ui_event_BluetoothTabView( lv_event_t * e);
lv_obj_t *ui_BluetoothTabView;
lv_obj_t *ui_BTConnectTabPage;
void ui_event_BTPairingButton( lv_event_t * e);
lv_obj_t *ui_BTPairingButton;
lv_obj_t *ui_Label9;
void ui_event_BTConnectButton( lv_event_t * e);
lv_obj_t *ui_BTConnectButton;
lv_obj_t *ui_Label10;
lv_obj_t *ui_BTInfoContainer;
lv_obj_t *ui_BTCameraNameLabel;
lv_obj_t *ui_BTCameraAddressLabel;
lv_obj_t *ui_BTConnectLabel;
lv_obj_t *ui_BTRemoteTabPage;
void ui_event_BTHalfPressButton( lv_event_t * e);
lv_obj_t *ui_BTHalfPressButton;
lv_obj_t *ui_Label12;
void ui_event_BTFullPressButton( lv_event_t * e);
lv_obj_t *ui_BTFullPressButton;
lv_obj_t *ui_Label13;
lv_obj_t *ui_Container11;
lv_obj_t *ui_BTWideButton;
lv_obj_t *ui_Label19;
lv_obj_t *ui_BTTeleButton;
lv_obj_t *ui_Label20;
lv_obj_t *ui_BTIntervalTabPane;
lv_obj_t *ui_PictureDigitRollerContainer;
lv_obj_t *ui_PRoller1000;
lv_obj_t *ui_PRoller100;
lv_obj_t *ui_PRoller10;
lv_obj_t *ui_PRoller1;
lv_obj_t *ui_IntervalDigitRollerContainer;
lv_obj_t *ui_IRoller100;
lv_obj_t *ui_IRoller10;
lv_obj_t *ui_IRoller1;
lv_obj_t *ui_IURoller;
lv_obj_t *ui_ExposureDigitRollerContainer;
lv_obj_t *ui_XRoller100;
lv_obj_t *ui_XRoller10;
lv_obj_t *ui_XRoller1;
lv_obj_t *ui_XURoller;
lv_obj_t *ui_IntervalProgressBar;
lv_obj_t *ui_IntervalProgressBarLabel;
lv_obj_t *ui_Label14;
lv_obj_t *ui_Label16;
lv_obj_t *ui_Label17;
void ui_event_BTIntStartButton( lv_event_t * e);
lv_obj_t *ui_BTIntStartButton;
lv_obj_t *ui_Image11;
void ui_event_BTIntPauseButton( lv_event_t * e);
lv_obj_t *ui_BTIntPauseButton;
lv_obj_t *ui_Image12;
void ui_event_BTIntStopButton( lv_event_t * e);
lv_obj_t *ui_BTIntStopButton;
lv_obj_t *ui_Image13;
void ui_event_CalHomeButton2( lv_event_t * e);
lv_obj_t *ui_CalHomeButton2;
lv_obj_t *ui_Image3;


// SCREEN: ui_CalibrationScreen
void ui_CalibrationScreen_screen_init(void);
void ui_event_CalibrationScreen( lv_event_t * e);
lv_obj_t *ui_CalibrationScreen;
lv_obj_t *ui_CalTitleLabel;
void ui_event_CalHomeButton( lv_event_t * e);
lv_obj_t *ui_CalHomeButton;
lv_obj_t *ui_Image10;
void ui_event_CalStartButton( lv_event_t * e);
lv_obj_t *ui_CalStartButton;
lv_obj_t *ui_Label15;
lv_obj_t *ui_CalInfoLabel1;
lv_obj_t *ui_Image5;
lv_obj_t *ui_Image6;
lv_obj_t *ui_Image1;
lv_obj_t *ui_CalInfoLabel2;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_bluetooth3_[1] = {&ui_img_bluetooth3_64_png};
const lv_img_dsc_t *ui_imgset_33616193[1] = {&ui_img_626158203};
const lv_img_dsc_t *ui_imgset_479143976[1] = {&ui_img_1463026258};
const lv_img_dsc_t *ui_imgset_1601800952[1] = {&ui_img_844469334};
const lv_img_dsc_t *ui_imgset_1605758535[1] = {&ui_img_1803052213};
const lv_img_dsc_t *ui_imgset_574278167[1] = {&ui_img_1941201141};
const lv_img_dsc_t *ui_imgset_273442535[1] = {&ui_img_766493279};
const lv_img_dsc_t *ui_imgset_wifi3_[1] = {&ui_img_wifi3_64_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_StartBluetoothButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_BluetoothScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_BluetoothScreen_screen_init);
}
}
void ui_event_Image2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_BluetoothScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_BluetoothScreen_screen_init);
}
}
void ui_event_ccApiCheckbox( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ccApiCheckboxClicked( e );
}
}
void ui_event_ptpCheckbox( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ptpCheckboxClicked( e );
}
}
void ui_event_RestartControllerButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      restartControllerButtonClicked( e );
}
}
void ui_event_CalibrateTouchPanelButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_CalibrationScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_CalibrationScreen_screen_init);
}
}
void ui_event_ResetAllSettingsButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      resetAllSettingsButtonClicked( e );
}
}
void ui_event_BluetoothScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      btScreenLoaded( e );
}
}
void ui_event_BluetoothTabView( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      btBluetoothTabViewValueChanged( e );
}
}
void ui_event_BTPairingButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btPairingClicked( e );
}
}
void ui_event_BTConnectButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btConnectButtonClicked( e );
}
}
void ui_event_BTHalfPressButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      btHalfPressedPressed( e );
}
if ( event_code == LV_EVENT_RELEASED) {
      btHalfPressedReleased( e );
}
}
void ui_event_BTFullPressButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      btFullPressedPressed( e );
}
if ( event_code == LV_EVENT_RELEASED) {
      btFullPressedReleased( e );
}
}
void ui_event_BTIntStartButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      intervalStartButtonClicked( e );
}
}
void ui_event_BTIntPauseButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      intervalPauseButtonClicked( e );
}
}
void ui_event_BTIntStopButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      intervalStopButtonClicked( e );
}
}
void ui_event_CalHomeButton2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_StartScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_StartScreen_screen_init);
}
}
void ui_event_CalibrationScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      calPointPressed( e );
}
}
void ui_event_CalHomeButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_StartScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_StartScreen_screen_init);
}
}
void ui_event_CalStartButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      calStartButtonClicked( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_StartScreen_screen_init();
ui_BluetoothScreen_screen_init();
ui_CalibrationScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_StartScreen);
}
