// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: CameraControl

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void startBluetooth(lv_event_t * e);
void startWiFi(lv_event_t * e);
void ccApiCheckboxClicked(lv_event_t * e);
void ptpCheckboxClicked(lv_event_t * e);
void restartControllerButtonClicked(lv_event_t * e);
void resetAllSettingsButtonClicked(lv_event_t * e);
void btScreenLoaded(lv_event_t * e);
void btBluetoothTabViewValueChanged(lv_event_t * e);
void btPairingClicked(lv_event_t * e);
void btConnectButtonClicked(lv_event_t * e);
void btHalfPressedPressed(lv_event_t * e);
void btHalfPressedReleased(lv_event_t * e);
void btFullPressedPressed(lv_event_t * e);
void btFullPressedReleased(lv_event_t * e);
void btWidePressed(lv_event_t * e);
void btWideReleased(lv_event_t * e);
void btTelePressed(lv_event_t * e);
void btTeleReleased(lv_event_t * e);
void intervalStartButtonClicked(lv_event_t * e);
void intervalPauseButtonClicked(lv_event_t * e);
void intervalStopButtonClicked(lv_event_t * e);
void calPointPressed(lv_event_t * e);
void calStartButtonClicked(lv_event_t * e);
void wifiScreenLoaded(lv_event_t * e);
void wifiScreenLoadStart(lv_event_t * e);
void wifiPasswordTextAreaClicked(lv_event_t * e);
void wifiNetworkScanClicked(lv_event_t * e);
void wifiConnectClicked(lv_event_t * e);
void wifiCameraIpAddressTextAreaClicked(lv_event_t * e);
void wifiCameraIpPortTextAreaClicked(lv_event_t * e);
void wifiKeyboardReadyClicked(lv_event_t * e);
void wifiKeyboardCancelClicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
