// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CameraControl

#include "../ui.h"

void ui_BluetoothScreen_screen_init(void)
{
ui_BluetoothScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_BluetoothScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BluetoothTabView = lv_tabview_create(ui_BluetoothScreen, LV_DIR_BOTTOM, 50);
lv_obj_set_width( ui_BluetoothTabView, 240);
lv_obj_set_height( ui_BluetoothTabView, 320);
lv_obj_set_x( ui_BluetoothTabView, 0 );
lv_obj_set_y( ui_BluetoothTabView, 2 );
lv_obj_set_align( ui_BluetoothTabView, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_BluetoothTabView, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


ui_BTConnectTabPage = lv_tabview_add_tab(ui_BluetoothTabView, "Connect");
lv_obj_set_flex_flow(ui_BTConnectTabPage,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_BTConnectTabPage, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

ui_BTPairingButton = lv_btn_create(ui_BTConnectTabPage);
lv_obj_set_width( ui_BTPairingButton, 100);
lv_obj_set_height( ui_BTPairingButton, 50);
lv_obj_set_align( ui_BTPairingButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTPairingButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BTPairingButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_BTPairingButton);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Pairing");

ui_BTConnectButton = lv_btn_create(ui_BTConnectTabPage);
lv_obj_set_width( ui_BTConnectButton, 100);
lv_obj_set_height( ui_BTConnectButton, 50);
lv_obj_set_align( ui_BTConnectButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTConnectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BTConnectButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label10 = lv_label_create(ui_BTConnectButton);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"Connect");

ui_BTInfoContainer = lv_obj_create(ui_BTConnectTabPage);
lv_obj_remove_style_all(ui_BTInfoContainer);
lv_obj_set_height( ui_BTInfoContainer, 99);
lv_obj_set_width( ui_BTInfoContainer, lv_pct(100));
lv_obj_set_align( ui_BTInfoContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_BTInfoContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_BTInfoContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_BTInfoContainer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BTCameraNameLabel = lv_label_create(ui_BTInfoContainer);
lv_obj_set_width( ui_BTCameraNameLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BTCameraNameLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BTCameraNameLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BTCameraNameLabel,"-");

ui_BTCameraAddressLabel = lv_label_create(ui_BTInfoContainer);
lv_obj_set_width( ui_BTCameraAddressLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BTCameraAddressLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BTCameraAddressLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BTCameraAddressLabel,"-");

ui_BTConnectLabel = lv_label_create(ui_BTInfoContainer);
lv_obj_set_width( ui_BTConnectLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BTConnectLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BTConnectLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BTConnectLabel,"Camera not connected!");

ui_BTRemoteTabPage = lv_tabview_add_tab(ui_BluetoothTabView, "Remote");
lv_obj_set_flex_flow(ui_BTRemoteTabPage,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_BTRemoteTabPage, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_BTRemoteTabPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BTHalfPressButton = lv_btn_create(ui_BTRemoteTabPage);
lv_obj_set_width( ui_BTHalfPressButton, 100);
lv_obj_set_height( ui_BTHalfPressButton, 50);
lv_obj_set_align( ui_BTHalfPressButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTHalfPressButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BTHalfPressButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label12 = lv_label_create(ui_BTHalfPressButton);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"Autofocus");

ui_BTFullPressButton = lv_btn_create(ui_BTRemoteTabPage);
lv_obj_set_width( ui_BTFullPressButton, 100);
lv_obj_set_height( ui_BTFullPressButton, 50);
lv_obj_set_align( ui_BTFullPressButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTFullPressButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BTFullPressButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label13 = lv_label_create(ui_BTFullPressButton);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"Shutter");

ui_Container11 = lv_obj_create(ui_BTRemoteTabPage);
lv_obj_remove_style_all(ui_Container11);
lv_obj_set_height( ui_Container11, 63);
lv_obj_set_width( ui_Container11, LV_SIZE_CONTENT);  /// 226
lv_obj_set_x( ui_Container11, 0 );
lv_obj_set_y( ui_Container11, -17 );
lv_obj_clear_flag( ui_Container11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BTWideButton = lv_btn_create(ui_Container11);
lv_obj_set_width( ui_BTWideButton, 50);
lv_obj_set_height( ui_BTWideButton, 50);
lv_obj_set_align( ui_BTWideButton, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_BTWideButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BTWideButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label19 = lv_label_create(ui_BTWideButton);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"Wide");

ui_BTTeleButton = lv_btn_create(ui_Container11);
lv_obj_set_width( ui_BTTeleButton, 50);
lv_obj_set_height( ui_BTTeleButton, 50);
lv_obj_set_x( ui_BTTeleButton, 60 );
lv_obj_set_y( ui_BTTeleButton, 0 );
lv_obj_set_align( ui_BTTeleButton, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_BTTeleButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BTTeleButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_BTTeleButton, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_BTTeleButton, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label20 = lv_label_create(ui_BTTeleButton);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"Tele");

ui_BTIntervalTabPane = lv_tabview_add_tab(ui_BluetoothTabView, "Interval");
lv_obj_clear_flag( ui_BTIntervalTabPane, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_pad_left(ui_BTIntervalTabPane, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_BTIntervalTabPane, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_BTIntervalTabPane, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_BTIntervalTabPane, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PictureDigitRollerContainer = lv_obj_create(ui_BTIntervalTabPane);
lv_obj_remove_style_all(ui_PictureDigitRollerContainer);
lv_obj_set_height( ui_PictureDigitRollerContainer, 64);
lv_obj_set_width( ui_PictureDigitRollerContainer, LV_SIZE_CONTENT);  /// 173
lv_obj_clear_flag( ui_PictureDigitRollerContainer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_PictureDigitRollerContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PictureDigitRollerContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PictureDigitRollerContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PictureDigitRollerContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PRoller1000 = lv_roller_create(ui_PictureDigitRollerContainer);
lv_roller_set_options( ui_PRoller1000, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_PRoller1000, 64);
lv_obj_set_width( ui_PRoller1000, LV_SIZE_CONTENT);  /// 1

lv_obj_set_style_bg_color(ui_PRoller1000, lv_color_hex(0x404040), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PRoller1000, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_PRoller100 = lv_roller_create(ui_PictureDigitRollerContainer);
lv_roller_set_options( ui_PRoller100, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_PRoller100, 64);
lv_obj_set_width( ui_PRoller100, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_PRoller100, 44 );
lv_obj_set_y( ui_PRoller100, 0 );

lv_obj_set_style_bg_color(ui_PRoller100, lv_color_hex(0x404040), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PRoller100, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_PRoller10 = lv_roller_create(ui_PictureDigitRollerContainer);
lv_roller_set_options( ui_PRoller10, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_PRoller10, 64);
lv_obj_set_width( ui_PRoller10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_PRoller10, 88 );
lv_obj_set_y( ui_PRoller10, 0 );

lv_obj_set_style_bg_color(ui_PRoller10, lv_color_hex(0x404040), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PRoller10, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_PRoller1 = lv_roller_create(ui_PictureDigitRollerContainer);
lv_roller_set_options( ui_PRoller1, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_PRoller1, 64);
lv_obj_set_width( ui_PRoller1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_PRoller1, 132 );
lv_obj_set_y( ui_PRoller1, 0 );

lv_obj_set_style_bg_color(ui_PRoller1, lv_color_hex(0x404040), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PRoller1, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_IntervalDigitRollerContainer = lv_obj_create(ui_BTIntervalTabPane);
lv_obj_remove_style_all(ui_IntervalDigitRollerContainer);
lv_obj_set_height( ui_IntervalDigitRollerContainer, 64);
lv_obj_set_width( ui_IntervalDigitRollerContainer, LV_SIZE_CONTENT);  /// 173
lv_obj_set_x( ui_IntervalDigitRollerContainer, 0 );
lv_obj_set_y( ui_IntervalDigitRollerContainer, 72 );
lv_obj_clear_flag( ui_IntervalDigitRollerContainer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_IRoller100 = lv_roller_create(ui_IntervalDigitRollerContainer);
lv_roller_set_options( ui_IRoller100, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_IRoller100, 64);
lv_obj_set_width( ui_IRoller100, LV_SIZE_CONTENT);  /// 1

lv_obj_set_style_bg_color(ui_IRoller100, lv_color_hex(0x404040), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_IRoller100, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_IRoller10 = lv_roller_create(ui_IntervalDigitRollerContainer);
lv_roller_set_options( ui_IRoller10, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_IRoller10, 64);
lv_obj_set_width( ui_IRoller10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_IRoller10, 44 );
lv_obj_set_y( ui_IRoller10, 0 );

lv_obj_set_style_bg_color(ui_IRoller10, lv_color_hex(0x404040), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_IRoller10, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_IRoller1 = lv_roller_create(ui_IntervalDigitRollerContainer);
lv_roller_set_options( ui_IRoller1, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_IRoller1, 64);
lv_obj_set_width( ui_IRoller1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_IRoller1, 88 );
lv_obj_set_y( ui_IRoller1, 0 );

lv_obj_set_style_bg_color(ui_IRoller1, lv_color_hex(0x404040), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_IRoller1, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_IURoller = lv_roller_create(ui_IntervalDigitRollerContainer);
lv_roller_set_options( ui_IURoller, "s\nm", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_IURoller, 64);
lv_obj_set_width( ui_IURoller, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_IURoller, 132 );
lv_obj_set_y( ui_IURoller, 0 );

lv_obj_set_style_bg_color(ui_IURoller, lv_color_hex(0x404080), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_IURoller, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_ExposureDigitRollerContainer = lv_obj_create(ui_BTIntervalTabPane);
lv_obj_remove_style_all(ui_ExposureDigitRollerContainer);
lv_obj_set_height( ui_ExposureDigitRollerContainer, 64);
lv_obj_set_width( ui_ExposureDigitRollerContainer, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ExposureDigitRollerContainer, 0 );
lv_obj_set_y( ui_ExposureDigitRollerContainer, 144 );
lv_obj_clear_flag( ui_ExposureDigitRollerContainer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_XRoller100 = lv_roller_create(ui_ExposureDigitRollerContainer);
lv_roller_set_options( ui_XRoller100, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_XRoller100, 64);
lv_obj_set_width( ui_XRoller100, LV_SIZE_CONTENT);  /// 1

lv_obj_set_style_bg_color(ui_XRoller100, lv_color_hex(0x404040), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_XRoller100, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_XRoller10 = lv_roller_create(ui_ExposureDigitRollerContainer);
lv_roller_set_options( ui_XRoller10, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_XRoller10, 64);
lv_obj_set_width( ui_XRoller10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_XRoller10, 44 );
lv_obj_set_y( ui_XRoller10, 0 );

lv_obj_set_style_bg_color(ui_XRoller10, lv_color_hex(0x404040), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_XRoller10, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_XRoller1 = lv_roller_create(ui_ExposureDigitRollerContainer);
lv_roller_set_options( ui_XRoller1, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_XRoller1, 64);
lv_obj_set_width( ui_XRoller1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_XRoller1, 88 );
lv_obj_set_y( ui_XRoller1, 0 );

lv_obj_set_style_bg_color(ui_XRoller1, lv_color_hex(0x404040), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_XRoller1, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_XURoller = lv_roller_create(ui_ExposureDigitRollerContainer);
lv_roller_set_options( ui_XURoller, "s\nm", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_XURoller, 64);
lv_obj_set_width( ui_XURoller, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_XURoller, 132 );
lv_obj_set_y( ui_XURoller, 0 );

lv_obj_set_style_bg_color(ui_XURoller, lv_color_hex(0x404080), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_XURoller, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_IntervalProgressBar = lv_bar_create(ui_BTIntervalTabPane);
lv_obj_set_width( ui_IntervalProgressBar, 240);
lv_obj_set_height( ui_IntervalProgressBar, 10);
lv_obj_set_x( ui_IntervalProgressBar, 0 );
lv_obj_set_y( ui_IntervalProgressBar, 212 );

ui_IntervalProgressBarLabel = lv_label_create(ui_IntervalProgressBar);
lv_obj_set_width( ui_IntervalProgressBarLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_IntervalProgressBarLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_IntervalProgressBarLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_IntervalProgressBarLabel,"0.0s");
lv_obj_set_style_text_color(ui_IntervalProgressBarLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_IntervalProgressBarLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_IntervalProgressBarLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label14 = lv_label_create(ui_BTIntervalTabPane);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label14, 183 );
lv_obj_set_y( ui_Label14, 36 );
lv_label_set_text(ui_Label14,"#P");
lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label16 = lv_label_create(ui_BTIntervalTabPane);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label16, 183 );
lv_obj_set_y( ui_Label16, 92 );
lv_label_set_text(ui_Label16,"IvT");
lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label17 = lv_label_create(ui_BTIntervalTabPane);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label17, 183 );
lv_obj_set_y( ui_Label17, 164 );
lv_label_set_text(ui_Label17,"XpT");
lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTIntStartButton = lv_btn_create(ui_BTIntervalTabPane);
lv_obj_set_width( ui_BTIntStartButton, 76);
lv_obj_set_height( ui_BTIntStartButton, 40);
lv_obj_set_x( ui_BTIntStartButton, 0 );
lv_obj_set_y( ui_BTIntStartButton, -4 );
lv_obj_set_align( ui_BTIntStartButton, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_BTIntStartButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BTIntStartButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image11 = lv_img_create(ui_BTIntStartButton);
lv_img_set_src(ui_Image11, &ui_img_1941201141);
lv_obj_set_width( ui_Image11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image11, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image11, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BTIntPauseButton = lv_btn_create(ui_BTIntervalTabPane);
lv_obj_set_width( ui_BTIntPauseButton, 76);
lv_obj_set_height( ui_BTIntPauseButton, 40);
lv_obj_set_x( ui_BTIntPauseButton, 0 );
lv_obj_set_y( ui_BTIntPauseButton, -4 );
lv_obj_set_align( ui_BTIntPauseButton, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_BTIntPauseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BTIntPauseButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BTIntPauseButton, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTIntPauseButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image12 = lv_img_create(ui_BTIntPauseButton);
lv_img_set_src(ui_Image12, &ui_img_1803052213);
lv_obj_set_width( ui_Image12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image12, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image12, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BTIntStopButton = lv_btn_create(ui_BTIntervalTabPane);
lv_obj_set_width( ui_BTIntStopButton, 76);
lv_obj_set_height( ui_BTIntStopButton, 40);
lv_obj_set_x( ui_BTIntStopButton, 0 );
lv_obj_set_y( ui_BTIntStopButton, -4 );
lv_obj_set_align( ui_BTIntStopButton, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_BTIntStopButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BTIntStopButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BTIntStopButton, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BTIntStopButton, lv_color_hex(0xC00000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTIntStopButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image13 = lv_img_create(ui_BTIntStopButton);
lv_img_set_src(ui_Image13, &ui_img_766493279);
lv_obj_set_width( ui_Image13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image13, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image13, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CalHomeButton2 = lv_btn_create(ui_BluetoothScreen);
lv_obj_set_width( ui_CalHomeButton2, 32);
lv_obj_set_height( ui_CalHomeButton2, 32);
lv_obj_set_x( ui_CalHomeButton2, 208 );
lv_obj_set_y( ui_CalHomeButton2, 0 );
lv_obj_add_flag( ui_CalHomeButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CalHomeButton2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CalHomeButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CalHomeButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CalHomeButton2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CalHomeButton2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CalHomeButton2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CalHomeButton2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_CalHomeButton2);
lv_img_set_src(ui_Image3, &ui_img_844469334);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 32
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_BTPairingButton, ui_event_BTPairingButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTConnectButton, ui_event_BTConnectButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTHalfPressButton, ui_event_BTHalfPressButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTFullPressButton, ui_event_BTFullPressButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTIntStartButton, ui_event_BTIntStartButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTIntPauseButton, ui_event_BTIntPauseButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTIntStopButton, ui_event_BTIntStopButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BluetoothTabView, ui_event_BluetoothTabView, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CalHomeButton2, ui_event_CalHomeButton2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BluetoothScreen, ui_event_BluetoothScreen, LV_EVENT_ALL, NULL);

}
