// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CameraControl

#include "../ui.h"

void ui_CalibrationScreen_screen_init(void)
{
ui_CalibrationScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_CalibrationScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CalTitleLabel = lv_label_create(ui_CalibrationScreen);
lv_obj_set_width( ui_CalTitleLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CalTitleLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CalTitleLabel, 0 );
lv_obj_set_y( ui_CalTitleLabel, 12 );
lv_obj_set_align( ui_CalTitleLabel, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_CalTitleLabel,"Touch-Panel\nCalibration");
lv_obj_set_style_text_align(ui_CalTitleLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CalTitleLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CalHomeButton = lv_btn_create(ui_CalibrationScreen);
lv_obj_set_width( ui_CalHomeButton, 32);
lv_obj_set_height( ui_CalHomeButton, 32);
lv_obj_set_align( ui_CalHomeButton, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_CalHomeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CalHomeButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CalHomeButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CalHomeButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CalHomeButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CalHomeButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CalHomeButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CalHomeButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image10 = lv_img_create(ui_CalHomeButton);
lv_img_set_src(ui_Image10, &ui_img_844469334);
lv_obj_set_width( ui_Image10, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Image10, LV_SIZE_CONTENT);   /// 32
lv_obj_set_align( ui_Image10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image10, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CalStartButton = lv_btn_create(ui_CalibrationScreen);
lv_obj_set_width( ui_CalStartButton, 100);
lv_obj_set_height( ui_CalStartButton, 50);
lv_obj_set_x( ui_CalStartButton, 0 );
lv_obj_set_y( ui_CalStartButton, 160 );
lv_obj_set_align( ui_CalStartButton, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_CalStartButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CalStartButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label15 = lv_label_create(ui_CalStartButton);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"Start");

ui_CalInfoLabel1 = lv_label_create(ui_CalibrationScreen);
lv_obj_set_width( ui_CalInfoLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CalInfoLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CalInfoLabel1, 0 );
lv_obj_set_y( ui_CalInfoLabel1, 80 );
lv_obj_set_align( ui_CalInfoLabel1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_CalInfoLabel1,"Touch point center:");
lv_obj_set_style_text_align(ui_CalInfoLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CalInfoLabel1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image5 = lv_img_create(ui_CalibrationScreen);
lv_img_set_src(ui_Image5, &ui_img_626158203);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_Image5, 104 );
lv_obj_set_y( ui_Image5, 288 );
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_Image6 = lv_img_create(ui_CalibrationScreen);
lv_img_set_src(ui_Image6, &ui_img_626158203);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 32
lv_obj_clear_flag( ui_Image6, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_Image1 = lv_img_create(ui_CalibrationScreen);
lv_img_set_src(ui_Image1, &ui_img_626158203);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_Image1, 208 );
lv_obj_set_y( ui_Image1, 144 );
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_CalInfoLabel2 = lv_label_create(ui_CalibrationScreen);
lv_obj_set_width( ui_CalInfoLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CalInfoLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CalInfoLabel2, 0 );
lv_obj_set_y( ui_CalInfoLabel2, 104 );
lv_obj_set_align( ui_CalInfoLabel2, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_CalInfoLabel2,"-");
lv_obj_set_style_text_align(ui_CalInfoLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CalInfoLabel2, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_CalHomeButton, ui_event_CalHomeButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CalStartButton, ui_event_CalStartButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CalibrationScreen, ui_event_CalibrationScreen, LV_EVENT_ALL, NULL);

}
